# Generated by Django 5.2.7 on 2025-11-16 04:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
