# Generated by Django 5.2.7 on 2025-11-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_alter_sale_date_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=150, verbose_name='Empresa')),
                ('address', models.CharField(max_length=250, verbose_name='Dirección')),
                ('contact_name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('phone', models.CharField(max_length=30, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['id'],
            },
        ),
    ]
