# Generated by Django 5.2.7 on 2025-11-25 16:51

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de compra')),
                ('observations', models.CharField(blank=True, max_length=250, null=True, verbose_name='Observaciones')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('received', 'Recibida')], default='pending', max_length=10, verbose_name='Estado')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.provider', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Cantidad')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio compra')),
                ('sale_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio venta')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Fecha vencimiento')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.purchase')),
            ],
            options={
                'verbose_name': 'Detalle de compra',
                'verbose_name_plural': 'Detalles de compras',
                'ordering': ['id'],
            },
        ),
    ]
